language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm run test
  - npm run cover
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
