language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - yarn
script:
  - yarn test
  - yarn cover
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: npm
  email: mouafa.king@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    repo: mouafa/malal
    branch: master